//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LunarCalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LunarCalendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Army Day 的本地化字符串。
        /// </summary>
        public static string ArmyDayText {
            get {
                return ResourceManager.GetString("ArmyDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Children&apos;s Day 的本地化字符串。
        /// </summary>
        public static string ChildrensDayText {
            get {
                return ResourceManager.GetString("ChildrensDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ChineseNumberText {
            get {
                return ResourceManager.GetString("ChineseNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ChongyangText {
            get {
                return ResourceManager.GetString("ChongyangText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 X&apos;mas 的本地化字符串。
        /// </summary>
        public static string ChristmasText {
            get {
                return ResourceManager.GetString("ChristmasText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ChushiText {
            get {
                return ResourceManager.GetString("ChushiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string ChuxiText {
            get {
                return ResourceManager.GetString("ChuxiText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        public static string CurrentMonthText {
            get {
                return ResourceManager.GetString("CurrentMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string DuanwuText {
            get {
                return ResourceManager.GetString("DuanwuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fri. 的本地化字符串。
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string HighOrderText {
            get {
                return ResourceManager.GetString("HighOrderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Labor Day 的本地化字符串。
        /// </summary>
        public static string LaborDayText {
            get {
                return ResourceManager.GetString("LaborDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LeapText {
            get {
                return ResourceManager.GetString("LeapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarApr {
            get {
                return ResourceManager.GetString("LunarApr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarAug {
            get {
                return ResourceManager.GetString("LunarAug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarDec {
            get {
                return ResourceManager.GetString("LunarDec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarFeb {
            get {
                return ResourceManager.GetString("LunarFeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarJan {
            get {
                return ResourceManager.GetString("LunarJan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarJul {
            get {
                return ResourceManager.GetString("LunarJul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarJun {
            get {
                return ResourceManager.GetString("LunarJun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarMar {
            get {
                return ResourceManager.GetString("LunarMar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarMay {
            get {
                return ResourceManager.GetString("LunarMay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarNov {
            get {
                return ResourceManager.GetString("LunarNov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarOct {
            get {
                return ResourceManager.GetString("LunarOct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LunarSep {
            get {
                return ResourceManager.GetString("LunarSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string MidautumnText {
            get {
                return ResourceManager.GetString("MidautumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mon. 的本地化字符串。
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 National Day 的本地化字符串。
        /// </summary>
        public static string NationalDayText {
            get {
                return ResourceManager.GetString("NationalDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Year&apos;s Day 的本地化字符串。
        /// </summary>
        public static string NewYearsDayText {
            get {
                return ResourceManager.GetString("NewYearsDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Month 的本地化字符串。
        /// </summary>
        public static string NextMonthText {
            get {
                return ResourceManager.GetString("NextMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next  Year 的本地化字符串。
        /// </summary>
        public static string NextYearText {
            get {
                return ResourceManager.GetString("NextYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev. Month 的本地化字符串。
        /// </summary>
        public static string PreviousMonthText {
            get {
                return ResourceManager.GetString("PreviousMonthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prev. Year 的本地化字符串。
        /// </summary>
        public static string PreviousYearText {
            get {
                return ResourceManager.GetString("PreviousYearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sat. 的本地化字符串。
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string SpringFestivalText {
            get {
                return ResourceManager.GetString("SpringFestivalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sun. 的本地化字符串。
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thu. 的本地化字符串。
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tue. 的本地化字符串。
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wed. 的本地化字符串。
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Youth Day 的本地化字符串。
        /// </summary>
        public static string YouthDayText {
            get {
                return ResourceManager.GetString("YouthDayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string YuanxiaoText {
            get {
                return ResourceManager.GetString("YuanxiaoText", resourceCulture);
            }
        }
    }
}
